### PR TITLE
start of DCC implementation

### PR DESCRIPTION
**Pull request by pidario**
This pull request enables DCC/XDCC downloads (#60).

As of now, no GUI has been made and the file is not streamed to the browser once it has finished downloading but it is saved in the folder specified in the configuration file.
Also, resume is still not supported: I believe it's better to wait for the GUI before implementing it.
Another missing feature that requires the GUI is the possibility to accept the download if in configuration the parameter `autoget` is `false`.

### CODE REVIEW

**Comment by khlieng** [comment]
Cool, I moved some things around. To make this usable until a UI is in place you could send something like: `i.state.sendJSON("pm", Message{Server: i.client.Host, From: "@dcc", Content: "status whatever / download link"}`. The @ in the nick makes it invalid so theres no collisions.

**Comment by pidario** [comment]
All right, I'll send a new commit ASAP

**Comment by pidario** [comment]
Done. I also added some tweaks.

**Comment by khlieng** [comment]
Is there anything more you'd like to do before we merge this?

**Comment by pidario** [comment]
I don't think so. In your last commit you asked if we need to send total bytes after the cycle ends. We probably don't, since the last iteration has already done it, but it's easily checkable: if the sending user correctly acknowledges the file as been correctly downloaded (usually they send a private msg to notify it), then we can remove that line.

**Pull request merged**
